import{useEffect,useMemo,useState}from"react";import{buildings,troops,research,Cost}from"./game/data";import{State,initial,tick,scale,canPay,pay,production,popCap,population,hospitalCap,power}from"./game/engine";
const KEY="rts-mvp-save-v1";
const labels:any={food:"Comida",wood:"Madeira",stone:"Pedra",iron:"Ferro",gold:"Ouro"};
function costText(c:Cost){return Object.entries(c).map(([k,v])=>`${labels[k]} ${v}`).join(" · ")}
export function App(){const[s,setS]=useState<State>(()=>{try{return JSON.parse(localStorage.getItem(KEY)||"")||initial()}catch{return initial()}});const[tab,setTab]=useState<"city"|"army"|"research"|"hospital">("city");const[selected,setSelected]=useState("castle");
useEffect(()=>{const id=setInterval(()=>setS(x=>({...tick(structuredClone(x))})),250);return()=>clearInterval(id)},[]);
useEffect(()=>localStorage.setItem(KEY,JSON.stringify(s)),[s]);
const prod=useMemo(()=>production(s),[s]);const pwr=power(s),pop=population(s),cap=popCap(s);
function mutate(fn:(n:State)=>void){setS(old=>{const n=structuredClone(old);fn(n);return n})}
function queueBuild(id:string){mutate(n=>{const b=buildings.find(x=>x.id===id)!;const lvl=n.levels[id]||0;const c=scale(b.cost,lvl+1);if(!canPay(n,c)||n.jobs.some(j=>j.id===id&&(j.kind==="build"||j.kind==="upgrade")))return;pay(n,c);n.jobs.push({kind:lvl?"upgrade":"build",id,ends:Date.now()+b.baseTime*1000*Math.pow(1.12,lvl)})})}
function train(id:string){mutate(n=>{const t=troops.find(x=>x.id===id)!;if(!n.levels[t.building]||population(n)>=popCap(n)||!canPay(n,t.cost))return;pay(n,t.cost);const speed=1+(n.research.logistics||0)*.04;n.jobs.push({kind:"train",id,qty:1,ends:Date.now()+t.time*1000/speed})})}
function study(id:string){mutate(n=>{if(!n.levels.academy)return;const r=research.find(x=>x.id===id)!;const lvl=n.research[id]||0,c=scale(r.cost,lvl+1,1.38);if(!canPay(n,c)||n.jobs.some(j=>j.kind==="research"))return;pay(n,c);n.jobs.push({kind:"research",id,ends:Date.now()+r.time*1000*Math.pow(1.08,lvl)})})}
function battle(){mutate(n=>{const size=population(n);if(!size)return;const w=Math.min(Math.max(1,Math.floor(size*(.12+Math.random()*.18))),hospitalCap(n));n.wounded+=w;let left=w;for(const t of troops){const q=n.army[t.id]||0;const take=Math.min(q,left);n.army[t.id]=q-take;left-=take;if(!left)break}})}
function heal(){mutate(n=>{const q=Math.min(n.wounded,10);if(!q)return;const c={food:q*8,gold:q*2};if(!canPay(n,c))return;pay(n,c);n.jobs.push({kind:"heal",id:"hospital",qty:q,ends:Date.now()+5000})})}
return <div className="game"><header><div className="brand">⚜️ <b>Reino de Valedouro</b><span>RTS MVP</span></div><div className="resources">{(Object.keys(s.resources)as any[]).map(k=><div><strong>{labels[k]}</strong><b>{Math.floor(s.resources[k])}</b><small>+{prod[k].toFixed(1)}/s</small></div>)}</div><div className="power">⚡ Poder <b>{pwr.toLocaleString()}</b><small>👥 {pop}/{cap}</small></div></header>
<nav>{[["city","Cidade"],["army","Exército"],["research","Academia"],["hospital","Hospital"]].map(([k,n])=><button className={tab===k?"active":""} onClick={()=>setTab(k as any)}>{n}</button>)}</nav>
<main>{tab==="city"&&<><section className="scene"><div className="ground">{buildings.map((b,i)=>{const lvl=s.levels[b.id]||0;const busy=s.jobs.find(j=>j.id===b.id&&(j.kind==="build"||j.kind==="upgrade"));return <button style={{left:`${8+(i%5)*18}%`,top:`${12+Math.floor(i/5)*48}%`}} className={"building "+(selected===b.id?"sel":"")} onClick={()=>setSelected(b.id)}><span>{lvl?b.icon:"➕"}</span><b>{lvl?b.name:"Lote vazio"}</b><small>{lvl?`Nível ${lvl}`:b.name}</small>{busy&&<em>⏳ {Math.max(0,Math.ceil((busy.ends-Date.now())/1000))}s</em>}</button>})}<div className="road r1"/><div className="road r2"/></div></section><aside>{(()=>{const b=buildings.find(x=>x.id===selected)!;const lvl=s.levels[b.id]||0,c=scale(b.cost,lvl+1);return <><h2>{b.icon} {b.name}</h2><p>{b.desc}</p><div className="stat"><span>Nível</span><b>{lvl}</b></div><div className="stat"><span>Bônus</span><b>{b.buff}</b></div><h3>{lvl?"Próxima melhoria":"Construção"}</h3><p className="cost">{costText(c)}</p><button className="primary" onClick={()=>queueBuild(b.id)}>{lvl?"Melhorar":"Construir"}</button></>})()}</aside></>}
{tab==="army"&&<section className="panel full"><div className="hero"><h1>⚔️ Exército</h1><p>População {pop}/{cap} · Poder militar incluído no poder total</p><button onClick={battle}>Simular batalha</button></div><div className="grid">{troops.map(t=><article><div className="big">{t.icon}</div><h3>{t.name}</h3><p>ATQ {t.atk} · DEF {t.def} · VIDA {t.hp}</p><p>Poder {t.power} · Possui <b>{s.army[t.id]||0}</b></p><small>{costText(t.cost)}</small><button onClick={()=>train(t.id)}>Treinar</button></article>)}</div></section>}
{tab==="research"&&<section className="panel full"><div className="hero"><h1>📜 Academia</h1><p>Pesquisas não têm limite de nível e aplicam bônus reais.</p></div><div className="grid">{research.map(r=>{const lvl=s.research[r.id]||0,c=scale(r.cost,lvl+1,1.38);return <article><div className="big">{r.icon}</div><h3>{r.name} <small>Nv. {lvl}</small></h3><p>{r.desc}</p><small>{costText(c)}</small><button onClick={()=>study(r.id)}>Pesquisar</button></article>})}</div></section>}
{tab==="hospital"&&<section className="panel full"><div className="hero"><h1>🏥 Hospital</h1><p>Feridos {s.wounded}/{hospitalCap(s)}. Batalhas simuladas enviam sobreviventes feridos para cá.</p><button onClick={heal}>Curar até 10</button></div><div className="hospitalArt">⚕️<b>{s.wounded}</b><span>soldados aguardando tratamento</span></div></section>}
</main><footer><div><b>Filas em andamento</b>{s.jobs.length? s.jobs.map(j=><span>⏳ {j.kind}: {j.id} · {Math.max(0,Math.ceil((j.ends-Date.now())/1000))}s</span>):<span>Nenhuma atividade</span>}</div><button className="danger" onClick={()=>{if(confirm("Reiniciar todo o reino?"))setS(initial())}}>Resetar reino</button></footer></div>}